# Generated by Django 2.1.1 on 2018-09-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180919_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(default='undefined', max_length=200)),
                ('collegeScore', models.PositiveSmallIntegerField(default='0')),
                ('collegeGrade', models.CharField(default='F', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='objectives',
            name='objectiveName',
            field=models.CharField(default='objective', max_length=200),
        ),
    ]
